HtmxCSRazor/HtmxCSRazor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HtmxCSRazor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

HtmxCSRazor/HtmxCSRazor/Pages/Index.cshtml.cs
using Htmx;
using HtmxCSRazor.Services;
using HtmxCSRazor.Todo;
using HtmxCSRazor.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HtmxCSRazor.Pages;

public class IndexModel(MessageService messageService, TodoService todoService) : PageModel
{
    public IActionResult OnGet()
    {
        if (Request.IsHtmx())
        {
            throw new NotImplementedException();
        }

        return Page();
    }

    public IActionResult OnGetMessages()
    {
        return GetMessagesView();
    }

    public async Task<IActionResult> OnGetAddMessageAsync([FromQuery] string chatText)
    {
        await messageService.AddMessage(chatText);
        return GetMessagesView();
    }

    public IActionResult GetMessagesView()
    {
        return ViewComponent(typeof(MessageListViewComponent));
    }

    public IActionResult OnGetTodos()
    {
        return GetTodosView();
    }

    public async Task<IActionResult> OnGetAddTodoAsync([FromQuery] string newTodo)
    {
        await todoService.AddTodo(new NewTodoItem(newTodo));
        return GetTodosView();
    }

    public async Task<IActionResult> OnGetUpdateTodoAsync(
        [FromQuery] string todoNewValue,
        [FromQuery] string id)
    {
        await todoService.UpdateTodo(int.Parse(id), new NewTodoItem(todoNewValue));
        return GetTodosView();
    }

    private IActionResult GetTodosView()
    {
        return ViewComponent(typeof(TodoListViewComponent));
    }
}

HtmxCSRazor/HtmxCSRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HtmxCSRazor.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

HtmxCSRazor/HtmxCSRazor/ViewComponents/MessageListViewComponent.cs
using HtmxCSRazor.Services;
using Microsoft.AspNetCore.Mvc;

namespace HtmxCSRazor.ViewComponents;

[ViewComponent]
public class MessageListViewComponent(MessageService messageService) : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View(messageService.GetMessages());
    }
}

HtmxCSRazor/HtmxCSRazor/ViewComponents/TodoListViewComponent.cs
using HtmxCSRazor.Todo;
using Microsoft.AspNetCore.Mvc;

namespace HtmxCSRazor.ViewComponents;

[ViewComponent]
public class TodoListViewComponent(TodoService todoService) : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View(todoService.GetTodos());
    }
}

HtmxCSRazor/HtmxCSRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="h-full flex flex-col">
    <partial name="_TodoPanel"/>
    <partial name="_ChatPanel"/>
</div>

HtmxCSRazor/HtmxCSRazor/Pages/Shared/Components/MessageList/Default.cshtml
@model IEnumerable<string>

@foreach(var message in Model)
{
    <div>@message</div>
}

HtmxCSRazor/HtmxCSRazor/Pages/Shared/Components/TodoList/Default.cshtml
@using HtmxCSRazor.Todo
@model IEnumerable<TodoItem>

@foreach (var todo in Model)
{
    <todo-item id="todo-@todo.Id" class="my-1">
        <div slot="display" id="todo-@todo.Id-display" class="content-display flex flex-row">
            <div class="mr-5">@todo.Text</div>
            <button class="btn" _="on click send toggleTodoState">Edit</button>
        </div>
        <div slot="edit" id="todo-@todo.Id-edit" class="content-edit flex flex-row">
            <form hx-target="#todos" hx-get="?handler=updatetodo" hx-swap="none">
                <input type="text" value="@todo.Text" name="todoNewValue" class="mr-5"/>
                <button type="submit" class="btn" _="on click send toggleTodoState">Save</button>
                <input type="hidden" name="id" value="@todo.Id"/>
            </form>
        </div>
    </todo-item>
}

HtmxCSRazor/HtmxCSRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - HtmxCSRazor</title>
    <link rel="stylesheet" href="~/css/index.css"/>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.2/dist/full.css" rel="stylesheet" type="text/css"/>
</head>
<body class="h-screen">
<main role="main" class="h-full">
    @RenderBody()
</main>

<script src="https://unpkg.com/htmx.org@1.9.6"></script>
<script src="https://unpkg.com/htmx.org/dist/ext/sse.js"></script>
<script src="https://cdn.tailwindcss.com"></script>
<script src="https://unpkg.com/idiomorph/dist/idiomorph-ext.min.js"></script>
<script src="https://unpkg.com/hyperscript.org@0.9.11"></script>

<script src="~/index.js" asp-append-version="true"></script>


@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HtmxCSRazor/HtmxCSRazor/Pages/_ChatPanel.cshtml
<div class="m-2 flex flex-col h-1/2">
    <h1 class="mb-3">Messages</h1>
    <div class="grow overflow-y-auto" hx-sse="connect:/messages-sse">
        <div id="messages" hx-ext="sse" hx-trigger="sse:update-message" hx-get="?handler=messages">
            <vc:message-list/>
        </div>
    </div>

    <div hx-target="#messages" class="px-10 my-10 flex" _="on htmx:afterRequest set #chatText.value to '' then call #chatText.focus()">
        <input hx-get="?handler=addmessage" type="text" id="chatText" name="chatText" hx-trigger="keydown[keyCode==13]" class="w-1/4 mr-10"/>
        <button hx-get="?handler=addmessage" hx-include="[name='chatText']" class="btn btn-primary">Send</button>
    </div>
</div>

HtmxCSRazor/HtmxCSRazor/Pages/_TodoPanel.cshtml
<div class="m-2 h-1/2 todo-container" hx-ext="morph">
    <h1 class="mb-3">Todos</h1>
    <div class="m-2 overflow-y-auto" hx-sse="connect:/messages-sse">
        <div id="todos" hx-ext="sse" hx-trigger="sse:update-todos" hx-get="?handler=todos" hx-swap="morph:innerHTML">
            <vc:todo-list/>
        </div>
    </div>

    <div hx-target="#todos" class="px-10 mb-10 flex" _="on htmx:afterRequest set #newTodo.value to '' then call #newTodo.focus()">
        <input hx-get="?handler=addtodo" type="text" id="newTodo" name="newTodo" hx-trigger="keydown[keyCode==13]" class="w-1/4 mr-10" hx-swap="morph:innerHTML"/>
        <button hx-get="?handler=addtodo" hx-include="[name='newTodo']" hx-swap="morph" class="btn btn-primary">Add</button>
    </div>
</div>